import Link from "next/link";
import type { Metadata } from "next";
import FaqAccordion from "@/components/ui/FaqAccordion";

export const metadata: Metadata = {
  title: "Masters Dissertation Topic Selection Services UK",
  description: "Expert Dissertation Topic Selection for master's students. Unique, research-oriented, feasible topics across all academic areas. UK & UAE specialists. Tutors India.",
};

const relatedServices = [
  { label: "Dissertation Proposal", href: "/our-services/masters-dissertation-writing-services/dissertation-proposal/" },
  { label: "Full Dissertation", href: "/our-services/masters-dissertation-writing-services/full-dissertation/" },
  { label: "Dissertation Part", href: "/our-services/masters-dissertation-writing-services/dissertation-part/" },
  { label: "Resit Dissertation", href: "/our-services/masters-dissertation-writing-services/resit-dissertation/" },
  { label: "Statistical Analysis", href: "/our-services/masters-dissertation-writing-services/dissertation-statistical-analysis/" },
  { label: "CV Writing", href: "/our-services/masters-dissertation-writing-services/cv-writing/" },
];

const keyFeatures = [
  { icon: "💡", title: "Topic Ideas Generated by Students", desc: "Our topic generation is based on student ideas by including the study area of the student into the picture. We understand your interests, background, and career goals before suggesting topics." },
  { icon: "🎓", title: "Help from Subject Matter Experts", desc: "Professional help to select good dissertation topics is available from our subject matter experts who hold PhD and Masters degrees from top UK and US universities." },
  { icon: "🌍", title: "Real-World Dissertation Topic Selection", desc: "Our help is useful for working professionals to select dissertation topics which have practical application in the real world and align with current industry trends." },
  { icon: "📊", title: "Database Analysis", desc: "Analysis of databases such as ProQuest, ScienceDirect, JSTOR, Emerald, IEEE, and Google Scholar are done by us to identify dissertation topics with genuine research gaps." },
];

const supportTiers = [
  {
    tier: "Starter",
    color: "#2563b0",
    title: "Starter Topic Ideas",
    desc: "Benefit from numerous topic proposals tailored to fit your field of study and personal preferences. Ideal for students at the very beginning of their research journey.",
    includes: ["5–10 unique topic suggestions", "Brief rationale for each topic", "Subject area coverage", "Feasibility assessment"],
  },
  {
    tier: "Advanced",
    color: "#1a2a6c",
    title: "Research-Based Topic Development",
    desc: "Benefit from a professionally selected topic proposal with defined goals and research methodologies with relevant academic literature references.",
    includes: ["Topic with defined research objectives", "Preliminary literature overview", "Research gap identification", "Methodology recommendation", "Background reading list"],
  },
  {
    tier: "Premium",
    color: "#e87722",
    title: "Topic Proposal at Its Best",
    desc: "Gain access to advanced dissertation topics including gap analysis, contribution to knowledge, and full academic guidance for supervisor approval.",
    includes: ["Complete gap analysis", "Contribution to knowledge statement", "Full academic guidance", "Supervisor approval strategy", "Topic refinement support"],
  },
];

const whyChoosePoints = [
  {
    title: "Complete Privacy & Confidentiality",
    icon: "🔒",
    points: [
      "Guaranteed total privacy for your personal, financial and assignment information",
      "Complete safety ensured while uploading your research papers",
      "Accessible only to expert academic professionals who have signed NDAs",
      "SSL encryption ensures maximum security measures",
    ],
  },
  {
    title: "Ethical & Quality-Focused Services",
    icon: "⭐",
    points: [
      "Reliable and credible scholarly articles and journals sources for topics",
      "The topics are relevant to present-day industrial issues",
      "The originality of topics is checked with the research scope",
      "We ensure genuine and professional assistance in topic formation",
    ],
  },
  {
    title: "Our Key Guarantees",
    icon: "✅",
    points: [
      "Available customer care services 24/7",
      "100% originality and quality topics guaranteed",
      "Topic assistance service with proper citation and references",
      "Professional and Expert Academic Writers",
    ],
  },
  {
    title: "Plagiarism-Free Research Support",
    icon: "🛡️",
    points: [
      "Individually crafted and thoroughly researched Dissertation Topics",
      "Evaluated completely using the best plagiarism detection software tools",
      "Topics are based on extensive research papers",
      "High quality and genuine academic assistance in topic formulation",
    ],
  },
  {
    title: "On-Time Academic Assistance",
    icon: "⏱",
    points: [
      "Your original topics delivered well before the deadline",
      "Instant modification service offered in case changes are needed",
      "We offer flexible editing options for all students",
      "Guidance provided at each stage of topic development",
    ],
  },
  {
    title: "Experienced Academic Writers",
    icon: "🎓",
    points: [
      "Well experienced academicians with expertise in research",
      "Expert knowledge in research papers writing",
      "Wide range of experience in diverse academic fields",
      "Certified professionals in respective academic disciplines",
    ],
  },
];

const qaBoxes = [
  { img: "/images/qa/Topic-Selection.png", title: "Your Topic Selection", desc: "Check the sample topic selection from our expert writers", href: "/our-sample-works/" },
  { img: "/images/qa/Quality-Assurance.png", title: "Quality Assurance", desc: "We ensure quality at every stage and the process.", href: "/guarantees/" },
  { img: "/images/qa/Plagiarism-Report.png", title: "Plagiarism Report", desc: "We deliver the document after scanning for plagiarism.", href: "/guarantees/" },
  { img: "/images/qa/Customer-Interaction.png", title: "Customer Interaction", desc: "We interact with the customer at every stage for amendments, queries and delivery.", href: "/contact-us/" },
];

const faqs = [
  { q: "Why is dissertation topic selection important for master's students?", a: "Choosing the right dissertation topic helps students develop strong research, analytical, and problem-solving skills while improving academic performance and future career opportunities. A strong topic sets the foundation for a successful dissertation journey." },
  { q: "Can I choose a dissertation topic related to my future career goals?", a: "Yes, selecting a topic connected to your career interests can enhance subject expertise, increase employability, and provide practical industry knowledge. Our experts help align your topic with both academic standards and professional ambitions." },
  { q: "How can expert guidance help in selecting a dissertation topic?", a: "Expert guidance helps students identify innovative, researchable, and career-focused topics that align with university standards and current industry trends. Our PhD-qualified team analyses research gaps in your field to ensure your topic is both original and feasible." },
  { q: "What makes a strong dissertation topic for UK and UAE universities?", a: "A strong dissertation topic should be original, academically relevant, manageable within the deadline, and supported by sufficient research resources. It must address a clear gap in existing literature and align with your university's assessment criteria." },
  { q: "Can dissertation topic selection improve job opportunities after graduation?", a: "Yes, choosing an industry-relevant dissertation topic can strengthen your professional profile, demonstrate specialised knowledge, and improve employment prospects. Our service is completely flexible to help you find the perfect balance between academic rigour and career relevance." },
  { q: "How do I know if my dissertation topic is researchable?", a: "A topic is considered researchable when there is enough academic literature, accessible data, clear objectives, and a realistic scope for analysis. Our experts conduct a feasibility assessment for every topic suggestion to ensure it can be completed within your deadline and word count." },
];

const testimonials = [
  { quote: "Topic selection was extraordinary, my professor approved on the first go. Good. I will sure recommend the service to all my class mates.", author: "C S", location: "Sheffield, UK" },
  { quote: "4 times my research topic is rejected so I contact tutors India, recommended by one of my friend. Thank you so much tutors India — such an impressive topic selection. I revert back for my further chapter writing support.", author: "B A", location: "London, UK" },
  { quote: "Thank you Tutors India for giving me wonderful topic selection, it got approved and further from research proposal to citation, I need the same support.", author: "K S", location: "Boston, US" },
  { quote: "I must confess I was not quite convinced when I received the topics from their professionals. I thought they were too specific. But then my guide appreciated me for being that specific! There was no looking back then. They did my proposal tremendously well. Great team, great work, fair prices!", author: "Divij", location: "UK" },
  { quote: "The service we receive is completely flexible. Tutors India provided me with a great deal of flexibility in terms of choosing courses and research areas. The specialists assisted me in choosing a unique and significant research topic, as well as moving on to the next stage of my research.", author: "N.M.", location: "US" },
  { quote: "Honestly, I didn't expect this level of quality. The team understood exactly what I needed and delivered work that felt genuinely professional. My confidence went from stressed to unstoppable.", author: "Amelia Brooks", location: "UK" },
];

const subjects = [
  "Arts & Humanities", "Biological Sciences", "Business & Management Studies",
  "Marketing & Communication", "Engineering & Technology", "Natural Sciences & Mathematics",
  "Biological & Life Science", "Economics & Administration", "Humanities & Social Science",
  "Law", "Medicine & Health", "Education & Training", "Journalism & Media",
  "Agriculture & Forestry", "Computer Science & IT", "Hospitality, Leisure & Sports",
];

export default function DissertationTopicPage() {
  return (
    <>
      {/* ── HERO ── */}
      <section style={{ background: "linear-gradient(135deg,#1a2a6c 0%,#2563b0 100%)", color: "#fff", padding: "64px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <div style={{ fontSize: "0.82rem", color: "#a0b8e0", marginBottom: "14px" }}>
            <Link href="/" style={{ color: "#a0b8e0" }}>Home</Link>{" / "}
            <Link href="/our-services/" style={{ color: "#a0b8e0" }}>Services</Link>{" / "}
            <Link href="/our-services/masters-dissertation-writing-services/" style={{ color: "#a0b8e0" }}>Masters Dissertation</Link>{" / "}
            <span style={{ color: "#fff" }}>Dissertation Topic</span>
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr auto", gap: "40px", alignItems: "center" }} className="hero-inner">
            <div>
              <h1 style={{ fontFamily: "Merriweather,serif", fontSize: "clamp(1.5rem,3vw,2.2rem)", lineHeight: 1.3, marginBottom: "16px" }}>
                Expert Dissertation Topic Selection for Master's Students
              </h1>
              <p style={{ color: "#c5d5f0", fontSize: "1rem", lineHeight: 1.75, marginBottom: "10px" }}>
                Topic selection for dissertation is an important element of success in academic writing. We offer master's Dissertation Topic Selection Services that will assist you in finding unique, research-oriented, and feasible topics in all academic areas.
              </p>
              <p style={{ color: "#a0b8e0", fontSize: "0.92rem", marginBottom: "26px" }}>
                Your chosen topic will have a research gap for sure! Then You've Certainly Reached the Right place.
              </p>
              <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
                <Link href="/order-now/" style={{ padding: "12px 30px", background: "#e87722", color: "#fff", borderRadius: "5px", fontWeight: 700 }}>Place an Order</Link>
                <Link href="/contact-us/" style={{ padding: "12px 30px", border: "2px solid rgba(255,255,255,0.5)", color: "#fff", borderRadius: "5px", fontWeight: 600 }}>Reach Our Experts</Link>
              </div>
            </div>
            <div style={{ background: "rgba(255,255,255,0.1)", border: "1px solid rgba(255,255,255,0.2)", borderRadius: "12px", padding: "24px 28px", textAlign: "center", minWidth: "180px" }} className="hero-badge">
              <img src="/tutorsindia-logo-hd.jpg" alt="Tutors India" style={{ width: "90px", height: "90px", objectFit: "contain", marginBottom: "10px" }} />
              <div style={{ fontSize: "1.4rem", fontWeight: 700, color: "#f9c74f" }}>2000+</div>
              <div style={{ fontSize: "0.8rem", color: "#c5d5f0" }}>Expert Researchers</div>
              <div style={{ fontSize: "0.75rem", color: "#a0b8e0", marginTop: "4px" }}>USA · UK · Australia<br />Canada · UAE &amp; more</div>
            </div>
          </div>
        </div>
        <style>{`@media(max-width:768px){.hero-inner{grid-template-columns:1fr!important;}.hero-badge{display:none!important;}}`}</style>
      </section>

      {/* ── STATS BAR ── */}
      <div style={{ background: "#12214a", padding: "16px 20px" }}>
        <div style={{ maxWidth: "1100px", margin: "0 auto", display: "flex", gap: "32px", flexWrap: "wrap", justifyContent: "center" }}>
          {[{ n: "2000+", l: "Expert Writers" }, { n: "2,00,000+", l: "Scholars Served" }, { n: "22+", l: "Years Experience" }, { n: "5–10", l: "Topic Suggestions" }, { n: "24h", l: "Delivery" }, { n: "30 min", l: "Response" }].map(s => (
            <div key={s.l} style={{ textAlign: "center" }}>
              <div style={{ fontSize: "1.1rem", fontWeight: 700, color: "#f9c74f" }}>{s.n}</div>
              <div style={{ fontSize: "0.68rem", color: "#a0b8e0", textTransform: "uppercase", letterSpacing: "0.05em" }}>{s.l}</div>
            </div>
          ))}
        </div>
      </div>

      {/* ── MAIN CONTENT ── */}
      <section style={{ maxWidth: "1200px", margin: "48px auto", padding: "0 20px" }}>
        <div>

          {/* Why Tutors India */}
          <div style={{ background: "#fff", border: "1px solid #dde2ef", borderRadius: "12px", padding: "32px", marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.35rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "14px" }}>
              Why Does Tutors India Lead in Dissertation Topic Guidance?
            </h2>
            <p style={{ color: "#555", lineHeight: 1.8, marginBottom: "14px", fontSize: "0.94rem" }}>
              At Tutors India, we assist you in choosing dissertation topics that are unique and have an element of research. We examine current trends in the field, any potential research gaps and make sure that the topics chosen by you meet university criteria. With our years of experience in academics, topic selection becomes easy for you.
            </p>
            <h3 style={{ fontFamily: "Merriweather,serif", fontSize: "1.15rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "12px" }}>
              Discover Unique Dissertation Topics with Strong Research Value
            </h3>
            <p style={{ color: "#555", lineHeight: 1.8, marginBottom: "14px", fontSize: "0.94rem" }}>
              Our company, Tutors India, assists students in the selection of dissertation topics, which are research-oriented and reflect the current trends in academics. The dissertation topics offered by our experts are structured very well and have academic significance along with well-defined research aims.
            </p>
            <p style={{ color: "#555", lineHeight: 1.8, fontSize: "0.94rem" }}>
              We specialise in MBA Dissertation Topic Selection Services in UK and master's Dissertation Topic Selection Help in UK — services that we provide according to various disciplines for the UK and UAE.
            </p>
          </div>

          {/* 4 Key Features */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginBottom: "24px" }} className="two-col-grid">
            {keyFeatures.map(f => (
              <div key={f.title} style={{ background: "#fff", border: "1px solid #dde2ef", borderRadius: "10px", padding: "20px" }}>
                <div style={{ fontSize: "1.8rem", marginBottom: "8px" }}>{f.icon}</div>
                <h3 style={{ fontSize: "0.95rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "6px" }}>{f.title}</h3>
                <p style={{ fontSize: "0.83rem", color: "#666", lineHeight: 1.6 }}>{f.desc}</p>
              </div>
            ))}
          </div>

          {/* Support Tiers */}
          <div style={{ marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.35rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "6px" }}>
              What Support Do We Provide for Dissertation Topic Selection?
            </h2>
            <p style={{ color: "#666", fontSize: "0.9rem", marginBottom: "18px" }}>Three tiers of topic selection support to match your academic stage</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: "16px" }} className="three-col-grid">
              {supportTiers.map(t => (
                <div key={t.tier} style={{ background: "#fff", border: `2px solid ${t.color}`, borderRadius: "10px", overflow: "hidden" }}>
                  <div style={{ background: t.color, color: "#fff", padding: "12px 16px" }}>
                    <div style={{ fontSize: "0.72rem", textTransform: "uppercase", letterSpacing: "0.08em", opacity: 0.8 }}>Tier</div>
                    <div style={{ fontSize: "1.1rem", fontWeight: 700 }}>{t.tier}</div>
                    <div style={{ fontSize: "0.85rem", fontWeight: 600 }}>{t.title}</div>
                  </div>
                  <div style={{ padding: "16px" }}>
                    <p style={{ fontSize: "0.82rem", color: "#555", lineHeight: 1.6, marginBottom: "12px" }}>{t.desc}</p>
                    <ul style={{ listStyle: "none", padding: 0 }}>
                      {t.includes.map(item => (
                        <li key={item} style={{ display: "flex", gap: "6px", fontSize: "0.78rem", color: "#555", padding: "4px 0", borderBottom: "1px solid #f0f2fa" }}>
                          <span style={{ color: "#e87722", fontWeight: 700, flexShrink: 0 }}>✓</span> {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* QA Boxes with images */}
          <div style={{ marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.35rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "18px" }}>
              Our Quality Assurance Process
            </h2>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "14px" }} className="four-col-grid">
              {qaBoxes.map(box => (
                <Link key={box.title} href={box.href} style={{ background: "#fff", border: "1px solid #dde2ef", borderRadius: "10px", overflow: "hidden", textAlign: "center", display: "block" }}>
                  <img src={box.img} alt={box.title} style={{ width: "100%", height: "100px", objectFit: "contain", padding: "10px", background: "#f5f6fa" }} loading="lazy" />
                  <div style={{ padding: "12px" }}>
                    <div style={{ fontSize: "0.85rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "4px" }}>{box.title}</div>
                    <div style={{ fontSize: "0.75rem", color: "#666", lineHeight: 1.5 }}>{box.desc}</div>
                  </div>
                </Link>
              ))}
            </div>
          </div>

          {/* Why Choose — 6 boxes */}
          <div style={{ marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.35rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "6px" }}>
              Why Choose Tutors India for Dissertation Topic Selection?
            </h2>
            <p style={{ color: "#666", fontSize: "0.9rem", marginBottom: "18px" }}>Expert researchers, plagiarism free services, unlimited revisions, round-the-clock help, and timely delivery of excellent dissertation topics.</p>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }} className="two-col-grid">
              {whyChoosePoints.map(w => (
                <div key={w.title} style={{ background: "#f5f6fa", borderRadius: "10px", padding: "20px", border: "1px solid #dde2ef" }}>
                  <div style={{ fontSize: "1.5rem", marginBottom: "8px" }}>{w.icon}</div>
                  <h3 style={{ fontSize: "0.95rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "10px" }}>{w.title}</h3>
                  <ul style={{ listStyle: "none", padding: 0 }}>
                    {w.points.map(p => (
                      <li key={p} style={{ display: "flex", gap: "6px", fontSize: "0.81rem", color: "#555", padding: "5px 0", borderBottom: "1px solid #e8eaf4" }}>
                        <span style={{ color: "#e87722", fontWeight: 700, flexShrink: 0 }}>→</span> {p}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* What Makes Our Topic Selection Effective */}
          <div style={{ background: "#fff", border: "1px solid #dde2ef", borderRadius: "12px", padding: "28px", marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.25rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "18px" }}>
              What Makes Our Topic Selection Effective?
            </h2>
            {[
              { title: "Dissertation Ideas According to Current Trends", desc: "Our experts assist students in coming up with original and innovative ideas to write their dissertations based on current trends in the world of academia. We also offer Professional Master's Topic Selection Services in UAE." },
              { title: "Enough Academic Background for the Topic", desc: "Our experts thoroughly examine related journals, case studies, and trustworthy database sources to come up with topics with enough academic background to support a full dissertation." },
              { title: "Choosing Topics for Successful Dissertation", desc: "Our team assists students in selecting topics that can be realistically achieved and that have practical approaches through realistic research goals and methods." },
              { title: "A Strong Topic Builds Strong Research", desc: "An effective research topic should be indicative of the quality of the research that was conducted. Our services include academic assistance and help you choose effective MBA Dissertation Topic Selection Help in UAE through professional reference materials." },
            ].map(item => (
              <div key={item.title} style={{ marginBottom: "16px", paddingBottom: "16px", borderBottom: "1px solid #f0f2fa" }}>
                <h3 style={{ fontSize: "0.95rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "5px" }}>{item.title}</h3>
                <p style={{ fontSize: "0.86rem", color: "#666", lineHeight: 1.65 }}>{item.desc}</p>
              </div>
            ))}
          </div>

          {/* FAQ */}
          <div style={{ marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.35rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "16px" }}>
              Frequently Asked Questions
            </h2>
            <FaqAccordion faqs={faqs} />
          </div>

          {/* Testimonials */}
          <div style={{ marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.35rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "16px" }}>
              What Our Clients Say
            </h2>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }} className="two-col-grid">
              {testimonials.map((t, i) => (
                <div key={i} style={{ background: "#fff", border: "1px solid #dde2ef", borderRadius: "10px", padding: "18px" }}>
                  <div style={{ color: "#e87722", fontSize: "2rem", lineHeight: 1, marginBottom: "6px", fontFamily: "serif" }}>&ldquo;</div>
                  <p style={{ color: "#555", fontSize: "0.85rem", lineHeight: 1.7, fontStyle: "italic", marginBottom: "12px" }}>{t.quote}</p>
                  <div style={{ fontWeight: 700, color: "#1a2a6c", fontSize: "0.85rem" }}>{t.author}</div>
                  {t.location && <div style={{ fontSize: "0.75rem", color: "#888" }}>{t.location}</div>}
                </div>
              ))}
            </div>
            <div style={{ textAlign: "center", marginTop: "16px" }}>
              <Link href="/testimonials/" style={{ padding: "9px 24px", border: "2px solid #1a2a6c", color: "#1a2a6c", borderRadius: "5px", fontWeight: 600, fontSize: "0.88rem" }}>View All Testimonials →</Link>
            </div>
          </div>

          {/* Subject Areas */}
          <div style={{ background: "#f5f6fa", borderRadius: "12px", padding: "24px", marginBottom: "24px" }}>
            <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.15rem", fontWeight: 700, color: "#1a2a6c", marginBottom: "6px" }}>
              Experts on Subject Matter in the UK and UAE
            </h2>
            <p style={{ color: "#666", fontSize: "0.87rem", marginBottom: "16px" }}>We employ more than 2000+ experts who specialise in different subjects and understand the standards established at universities within the UK and UAE.</p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
              {subjects.map(s => (
                <span key={s} style={{ padding: "5px 14px", background: "#fff", border: "1.5px solid #dde2ef", borderRadius: "16px", fontSize: "0.8rem", color: "#1a2a6c", fontWeight: 500 }}>{s}</span>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── CTA BANNER ── */}
      <section style={{ background: "#e87722", color: "#fff", padding: "52px 20px", textAlign: "center" }}>
        <h2 style={{ fontSize: "clamp(1.4rem,3vw,1.9rem)", fontWeight: 700, marginBottom: "10px" }}>
          Start Your Dissertation Journey with a Winning Topic
        </h2>
        <p style={{ fontSize: "0.95rem", color: "rgba(255,255,255,0.88)", marginBottom: "22px" }}>
          Join 2,00,000+ scholars who have trusted Tutors India since 2001. Response within 30 minutes.
        </p>
        <div style={{ display: "flex", gap: "14px", justifyContent: "center", flexWrap: "wrap" }}>
          <Link href="/order-now/" style={{ padding: "12px 32px", background: "#fff", color: "#e87722", borderRadius: "5px", fontWeight: 700 }}>Order Now</Link>
          <Link href="/contact-us/" style={{ padding: "12px 32px", border: "2px solid #fff", color: "#fff", borderRadius: "5px", fontWeight: 700 }}>Contact Us</Link>
        </div>
      </section>
    </>
  );
}
