import type { Metadata } from "next";
import Link from "next/link";
import FaqAccordion from "@/components/ui/FaqAccordion";
import TestimonialSlider from "@/components/ui/TestimonialSlider";

export const metadata: Metadata = {
  title: "Master's Dissertation Topic Selection Services in UK, UAE",
  description: "Get expert master’s Dissertation Topic Selection Services in the UK & UAE to choose unique, high-scoring, and university-approved research topics fast.",
  keywords: "master's dissertation topic selection services in UK, master's dissertation topic selection help in UAE, master's dissertation topic help, master's thesis topics service, master's thesis topics help, custom dissertation topic writing services, master's dissertation topic writing services UK, master's dissertation topic writing help UAE",
  alternates: { canonical: "https://tutorsindia.com/our-services/masters-dissertation-writing-services/dissertation-topic/" },
};

const keyFeatures = [
  { no: "1", title: "Topic Ideas Generated by Students", desc: "Our topic generation is based on student ideas by including the study area of the student into the picture." },
  { no: "2", title: "Help from Subject Matter Experts", desc: "Professional help to select good dissertation topics is available from our subject matter experts." },
  { no: "3", title: "Real-World Dissertation Topic Selection", desc: "Our help is useful for working professionals to select dissertation topics which have practical application in the real world." },
  { no: "4", title: "Database Analysis", desc: "Analysis of databases such as ProQuest, ScienceDirect, JSTOR, Emerald, IEEE, and Google Scholar are done by us to identify dissertation topics." },
];

const supportTiers = [
  {
    tier: "Starter",
    color: "#2563b0",
    title: "Starter Topic Ideas",
    desc: "Benefit from numerous topic proposals tailored to fit your field of study and personal preferences. Ideal for students at the very beginning of their research journey.",
    includes: ["5–10 unique topic suggestions", "Brief rationale for each topic", "Subject area coverage", "Feasibility assessment"],
  },
  {
    tier: "Advanced",
    color: "#1a2a6c",
    title: "Research-Based Topic Development",
    desc: "Benefit from a professionally selected topic proposal with defined goals and research methodologies with relevant academic literature references.",
    includes: ["Topic with defined research objectives", "Preliminary literature overview", "Research gap identification", "Methodology recommendation", "Background reading list"],
  },
  {
    tier: "Premium",
    color: "#e87722",
    title: "Topic Proposal at Its Best",
    desc: "Gain access to advanced dissertation topics including gap analysis, contribution, and academic guidance for the highest level of research success.",
    includes: ["Comprehensive gap analysis", "Contribution to knowledge", "Full academic justification", "Supervisor-ready presentation", "Gantt chart outline", "Subject expert consultation"],
  },
];

const effectivePoints = [
  { title: "Dissertation Ideas According to Current Trends", desc: "Our experts assist students in coming up with original and innovative ideas to write their dissertations based on current trends in the world of academia. We also offer Professional Master's Topic Selection Services in UAE in case you require our help in choosing your topic." },
  { title: "Enough Academic Background for the Topic", desc: "Our experts thoroughly examine related journals, case studies, and trustworthy database sources to come up with topics with enough academic background." },
  { title: "Choosing Topics for Successful Dissertation", desc: "Our team assists students in selecting topics that can be realistically achieved and that have practical approaches through realistic research goals and methods." },
];

const guarantees = [
  {
    icon: "🔒",
    title: "Complete Privacy & Confidentiality",
    points: [
      "Guaranteed total privacy for your personal, finance and assignment information",
      "Complete safety ensured while uploading your research papers and during copyrighting procedure",
      "Accessible only to expert academic professionals",
      "SSL encryption ensures maximum security measures",
    ],
  },
  {
    icon: "✅",
    title: "Ethical & Quality-Focused Services",
    points: [
      "Reliable and credible scholarly articles and journals sources for topics",
      "The topics are relevant to present-day industrial issues",
      "The originality of topics is checked with the research scope too",
      "We ensure genuine and professional assistance in topic formation",
    ],
  },
  {
    icon: "⭐",
    title: "Our Key Guarantees",
    points: [
      "Available customer care services 24/7",
      "100% originality and quality topics guaranteed",
      "Topic assistance service with proper citation and references",
      "Professional and Expert Academic Writers",
    ],
  },
  {
    icon: "📄",
    title: "Plagiarism-Free Research Support",
    points: [
      "Individually crafted and thoroughly researched for Dissertation Topics",
      "Evaluates completely using the best plagiarism detection software tools",
      "Our topics are based on extensive research papers",
      "High quality and genuine academic assistance in topic formulation",
    ],
  },
  {
    icon: "⏱",
    title: "On-Time Academic Assistance",
    points: [
      "Your original topics delivered well before the deadline",
      "Instant modification service offered in case changes are needed in your topic",
      "We offer flexible editing options for all students",
      "Guidance provided at each stage",
    ],
  },
  {
    icon: "👨‍🎓",
    title: "Experienced Academic Writers",
    points: [
      "Well experienced academicians with expertise in research",
      "Expert knowledge in research papers writing",
      "Wide range of experience in diverse academic fields",
      "Certified professionals in respective academic disciplines",
    ],
  },
];

const qaBoxes = [
  { img: "/images/qa/Topic-Selection.png", title: "Your Topic Selection", desc: "Check the sample topic selection from our expert writers", href: "/our-sample-works/" },
  { img: "/images/qa/Quality-Assurance.png", title: "Quality Assurance", desc: "We ensure quality at every stage and the process.", href: "/guarantees/" },
  { img: "/images/qa/Plagiarism-Report.png", title: "Plagiarism Report", desc: "We deliver the document after scanning for plagiarism", href: "/guarantees/" },
  { img: "/images/qa/Customer-Interaction.png", title: "Customer Interaction", desc: "We interact with the customer at every stage in terms of amendments, query and delivery.", href: "/contact-us/" },
];

const faqs = [
  { q: "Why is dissertation topic selection important for master's students?", a: "Choosing the right dissertation topic helps students develop strong research, analytical, and problem-solving skills while improving academic performance and future career opportunities." },
  { q: "Can I choose a dissertation topic related to my future career goals?", a: "Yes, selecting a topic connected to your career interests can enhance subject expertise, increase employability, and provide practical industry knowledge." },
  { q: "How can expert guidance help in selecting a dissertation topic?", a: "Expert guidance helps students identify innovative, researchable, and career-focused topics that align with university standards and current industry trends." },
  { q: "What makes a strong dissertation topic for UK and UAE universities?", a: "A strong dissertation topic should be original, academically relevant, manageable within the deadline, and supported by sufficient research resources." },
  { q: "Can dissertation topic selection improve job opportunities after graduation?", a: "The service we provide is completely flexible. Hence, yes, choosing an industry-relevant dissertation topic can strengthen your professional profile, demonstrate specialized knowledge, and improve employment prospects." },
  { q: "How do I know if my dissertation topic is researchable?", a: "A topic is considered researchable when there is enough academic literature, accessible data, clear objectives, and a realistic scope for analysis." },
];

const testimonials = [
  { quote: "I must confess I was not quite convinced when I received the topics from their professionals. I thought they were too specific. But then my guide appreciated me for being that specific! They did my proposal tremendously well. They stood by me until my thesis was finally accepted. Great team, great work, fair prices! Thank you Tutors India.", name: "Divij", location: "UK" },
  { quote: "Topic selection was extraordinary, my professor approved on the first go. Good. I will sure recommend the service to all my class mates.", name: "C S", location: "Sheffield, UK" },
  { quote: "4 times my research topic is rejected so I contact Tutors India, recommended by one of my friend, thank you so much Tutors India such an impressive topic selection. I revert back for my further chapter writing support.", name: "B A", location: "London, UK" },
  { quote: "Thank you Tutors India for giving me wonderful topic selection, it got approved and further from research proposal to citation, I need a same support.", name: "K S", location: "US, Boston" },
  { quote: "Tutors India provides me with a great deal of flexibility in terms of choosing courses and research areas. The specialists assisted me in choosing a unique and significant research topic, as well as moving on to the next stage of my research.", name: "N.M.", location: "U.S" },
];

const subjects = [
  "Arts & Humanities", "Biological Sciences", "Business & Management Studies",
  "Marketing & Communication", "Engineering & Technology", "Natural Sciences & Mathematics",
  "Biological & Life Science", "Economics & Administration", "Humanities & Social Science",
  "Law", "Medicine & Health", "Education & Training", "Journalism & Media",
  "Agriculture & Forestry", "Computer Science & IT", "Hospitality, Leisure & Sports",
];

const relatedServices = [
  { label: "Dissertation Proposal", href: "/our-services/masters-dissertation-writing-services/dissertation-proposal/" },
  { label: "Full Dissertation", href: "/our-services/masters-dissertation-writing-services/full-dissertation/" },
  { label: "Dissertation Part", href: "/our-services/masters-dissertation-writing-services/dissertation-part/" },
  { label: "Resit Dissertation", href: "/our-services/masters-dissertation-writing-services/resit-dissertation/" },
  { label: "Statistical Analysis", href: "/our-services/masters-dissertation-writing-services/dissertation-statistical-analysis/" },
  { label: "CV Writing", href: "/our-services/masters-dissertation-writing-services/cv-writing/" },
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map(f => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

export default function DissertationTopicPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      {/* Hero */}
      <section style={{ background: "linear-gradient(135deg,#1a2a6c 0%,#2563b0 100%)", color: "#fff", padding: "64px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <div style={{ fontSize: "0.82rem", color: "#a0b8e0", marginBottom: "14px" }}>
            <Link href="/" style={{ color: "#a0b8e0" }}>Home</Link>{" / "}
            <Link href="/our-services/" style={{ color: "#a0b8e0" }}>Our Services</Link>{" / "}
            <Link href="/our-services/masters-dissertation-writing-services/" style={{ color: "#a0b8e0" }}>Masters Dissertation</Link>{" / "}
            <span style={{ color: "#fff" }}>Dissertation Topic</span>
          </div>
          <h1 style={{ fontFamily: "Merriweather,serif", fontSize: "clamp(1.6rem,3vw,2.4rem)", marginBottom: "18px", lineHeight: 1.3 }}>
            Expert Dissertation Topic Selection for Master&apos;s Students
          </h1>
          <p style={{ color: "#c5d5f0", fontSize: "1.05rem", maxWidth: "780px", lineHeight: 1.8, marginBottom: "12px" }}>
            Topic selection for dissertation is an important element of success in academic writing. We offer master&apos;s Dissertation Topic Selection Services that will assist you in finding unique, research-oriented, and feasible topics in all academic areas. Our topic selection services come with professional help and topic recommendations according to the latest research trends.
          </p>
          <p style={{ color: "#c5d5f0", fontSize: "1rem", maxWidth: "780px", lineHeight: 1.8, marginBottom: "28px" }}>
            Benefit from the assistance of our dissertation writers in topic selection. Your chosen topic will have a research gap for sure!
          </p>
          <div style={{ display: "flex", gap: "14px", flexWrap: "wrap" }}>
            <Link href="/order-now/" style={{ padding: "12px 32px", background: "#e87722", color: "#fff", borderRadius: "5px", fontWeight: 700, fontSize: "0.95rem" }}>Place an Order</Link>
            <Link href="/contact-us/" style={{ padding: "12px 32px", border: "2px solid rgba(255,255,255,0.5)", color: "#fff", borderRadius: "5px", fontWeight: 600, fontSize: "0.95rem" }}>Then You&apos;ve Certainly Reached the Right Place</Link>
          </div>
        </div>
      </section>

      {/* Perfect Dissertation Topics */}
      <section style={{ maxWidth: "1200px", margin: "56px auto", padding: "0 20px" }}>
        <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.5rem", color: "#1a2a6c", marginBottom: "10px" }}>
          Perfect Dissertation Topics for UK &amp; UAE Students
        </h2>
        <p style={{ color: "#555", marginBottom: "32px", fontSize: "1rem", lineHeight: 1.8 }}>
          Our professionals assist students in selecting dissertation topics that are unique and research oriented.
        </p>

        <h3 style={{ fontFamily: "Merriweather,serif", fontSize: "1.2rem", color: "#1a2a6c", marginBottom: "12px" }}>
          Why Does Tutors India Lead in Dissertation Topic Guidance for the Students in UK &amp; UAE?
        </h3>
        <p style={{ color: "#444", lineHeight: 1.8, marginBottom: "28px" }}>
          At Tutors India, we assist you in choosing dissertation topics that are unique and have an element of research. We examine current trends in the field, any potential research gaps and make sure that the topics chosen by you meet university criteria. With our years of experience in academics, topic selection becomes easy for you. The best Dissertation Topic Selection Services in UK will guide you to start your research journey.
        </p>

        <h3 style={{ fontFamily: "Merriweather,serif", fontSize: "1.2rem", color: "#1a2a6c", marginBottom: "12px" }}>
          Discover Unique Dissertation Topics with Strong Research Value
        </h3>
        <p style={{ color: "#444", lineHeight: 1.8, marginBottom: "32px" }}>
          Our company, Tutors India, assists students in the selection of dissertation topics, which are research-oriented and reflect the current trends in academics. The dissertation topics offered by our experts are structured very well and have academic significance along with well-defined research aims. We also specialized in MBA Dissertation Topic Selection Services in UK and master&apos;s Dissertation Topic Selection Help in UK are some services that we provide according to various disciplines for the country of UK and UAE.
        </p>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: "24px" }}>
          {keyFeatures.map(f => (
            <div key={f.no} style={{ background: "#f5f7ff", border: "1px solid #dde2ef", borderRadius: "10px", padding: "24px" }}>
              <div style={{ width: "40px", height: "40px", background: "#1a2a6c", color: "#fff", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: "1.1rem", marginBottom: "14px" }}>{f.no}</div>
              <h3 style={{ fontFamily: "Merriweather,serif", fontSize: "1rem", color: "#1a2a6c", marginBottom: "8px" }}>{f.title}</h3>
              <p style={{ color: "#555", fontSize: "0.92rem", lineHeight: 1.7 }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* UK/UAE Topic Selection + Explore Diverse */}
      <section style={{ background: "#f0f4ff", padding: "48px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.4rem", color: "#1a2a6c", marginBottom: "10px" }}>
            UK/UAE Dissertation Topic Selection for Master&apos;s Students
          </h2>
          <p style={{ color: "#555", lineHeight: 1.8, marginBottom: "32px" }}>
            Selecting the right dissertation topic is essential for developing research, analytical, and professional skills that support academic success and future career opportunities.
          </p>
          <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.4rem", color: "#1a2a6c", marginBottom: "10px" }}>
            Explore Diverse Dissertation Topics for UK &amp; UAE Universities
          </h2>
          <p style={{ color: "#555", lineHeight: 1.8 }}>
            Our professionals select relevant topics for your dissertation that will not only be feasible but also unique and backed up with strong academic literature. Our topics are tailored according to your interests and future objectives.
          </p>
        </div>
      </section>

      {/* Support Tiers */}
      <section style={{ maxWidth: "1200px", margin: "56px auto", padding: "0 20px" }}>
        <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.5rem", color: "#1a2a6c", textAlign: "center", marginBottom: "8px" }}>
          What Support Do We Provide for Dissertation Topic Selection?
        </h2>
        <h3 style={{ textAlign: "center", color: "#1a2a6c", fontFamily: "Merriweather,serif", fontSize: "1.1rem", marginBottom: "8px" }}>
          Specialized Dissertation Topic Expertise Across Multiple Disciplines
        </h3>
        <p style={{ textAlign: "center", color: "#555", marginBottom: "36px" }}>
          Tutors India provides professional assistance in choosing MBA dissertation topics for the following disciplines — Management, Social Sciences, Engineering, Technology, Medical, Life Sciences, Arts and many others. Our professional Dissertation Topic Selection Help in UAE supports students in choosing academically relevant and research-driven topics tailored to their field of study.
        </p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: "24px" }}>
          {supportTiers.map(t => (
            <div key={t.tier} style={{ background: "#fff", borderRadius: "12px", overflow: "hidden", boxShadow: "0 2px 12px rgba(26,42,108,0.08)" }}>
              <div style={{ background: t.color, color: "#fff", padding: "18px 24px" }}>
                <div style={{ fontSize: "0.75rem", fontWeight: 700, letterSpacing: "1px", opacity: 0.8, marginBottom: "4px" }}>{t.tier.toUpperCase()}</div>
                <div style={{ fontFamily: "Merriweather,serif", fontSize: "1.05rem", fontWeight: 700 }}>{t.title}</div>
              </div>
              <div style={{ padding: "20px 24px" }}>
                <p style={{ color: "#555", fontSize: "0.96rem", lineHeight: 1.7, marginBottom: "16px" }}>{t.desc}</p>
                <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
                  {t.includes.map(item => (
                    <li key={item} style={{ display: "flex", gap: "8px", alignItems: "flex-start", color: "#444", fontSize: "0.94rem", marginBottom: "6px" }}>
                      <span style={{ color: t.color, fontWeight: 700, flexShrink: 0 }}>✓</span>{item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>
        <div style={{ textAlign: "center", marginTop: "32px" }}>
          <Link href="/order-now/" style={{ padding: "12px 36px", background: "#e87722", color: "#fff", borderRadius: "5px", fontWeight: 700 }}>Order Now</Link>
        </div>
      </section>

      {/* Well-Researched by Qualified Professionals */}
      <section style={{ background: "#f0f4ff", padding: "48px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.4rem", color: "#1a2a6c", marginBottom: "10px" }}>
            Well-Researched Dissertation Topics Selected by Qualified Professionals
          </h2>
          <p style={{ color: "#555", lineHeight: 1.8 }}>
            We choose our dissertation topics based on the recommendations from qualified experts in academia, who have extensive knowledge in research methodologies and specific subject matters.
          </p>
        </div>
      </section>

      {/* What Makes Our Topic Selection Effective */}
      <section style={{ maxWidth: "1200px", margin: "56px auto", padding: "0 20px" }}>
        <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.5rem", color: "#1a2a6c", marginBottom: "32px" }}>
          What Makes Our Topic Selection Support Effective?
        </h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: "20px", marginBottom: "40px" }}>
          {effectivePoints.map(p => (
            <div key={p.title} style={{ borderLeft: "4px solid #e87722", paddingLeft: "16px" }}>
              <h3 style={{ fontFamily: "Merriweather,serif", fontSize: "1rem", color: "#1a2a6c", marginBottom: "6px" }}>{p.title}</h3>
              <p style={{ color: "#555", fontSize: "0.96rem", lineHeight: 1.7 }}>{p.desc}</p>
            </div>
          ))}
        </div>

        <div style={{ background: "#f5f7ff", border: "1px solid #dde2ef", borderRadius: "10px", padding: "28px 32px", marginBottom: "20px" }}>
          <h3 style={{ fontFamily: "Merriweather,serif", fontSize: "1.15rem", color: "#1a2a6c", marginBottom: "10px" }}>
            A Strong Topic Builds Strong Research
          </h3>
          <p style={{ color: "#555", lineHeight: 1.8 }}>
            An effective research topic should be indicative of the quality of the research that was conducted. Our services include academic assistance and help you choose effective MBA Dissertation Topic Selection Help in UAE through professional reference materials.
          </p>
        </div>

        <div style={{ background: "#1a2a6c", color: "#fff", borderRadius: "10px", padding: "24px 32px" }}>
          <p style={{ fontFamily: "Merriweather,serif", fontSize: "1rem", fontWeight: 700, marginBottom: "6px" }}>
            Our topic selection service is exclusive
          </p>
          <p style={{ color: "#c5d5f0", fontSize: "0.95rem" }}>
            as we do not just provide topics, but the rather clear explanation and justification for the choice
          </p>
        </div>
      </section>

      {/* QA Boxes */}
      <section style={{ background: "#f0f4ff", padding: "48px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: "20px" }}>
            {qaBoxes.map(q => (
              <Link key={q.title} href={q.href} style={{ background: "#fff", borderRadius: "10px", padding: "24px", textAlign: "center", textDecoration: "none", boxShadow: "0 2px 8px rgba(0,0,0,0.06)", display: "block" }}>
                <img src={q.img} alt={q.title} style={{ height: "64px", objectFit: "contain", marginBottom: "12px" }} />
                <div style={{ fontWeight: 700, color: "#1a2a6c", fontSize: "0.95rem", marginBottom: "6px" }}>{q.title}</div>
                <div style={{ color: "#666", fontSize: "0.85rem" }}>{q.desc}</div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Guarantees */}
      <section style={{ maxWidth: "1200px", margin: "56px auto", padding: "0 20px" }}>
        <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.5rem", color: "#1a2a6c", marginBottom: "8px" }}>
          Why Choose Tutors India for Dissertation Topic Selection?
        </h2>
        <p style={{ color: "#555", marginBottom: "32px" }}>
          Expert researchers, plagiarism free services, unlimited revisions, round-the-clock help, and timely delivery of excellent dissertation topics.
        </p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: "20px" }}>
          {guarantees.map(g => (
            <div key={g.title} style={{ background: "#f5f7ff", border: "1px solid #dde2ef", borderRadius: "10px", padding: "20px 24px" }}>
              <div style={{ display: "flex", gap: "12px", alignItems: "center", marginBottom: "12px" }}>
                <span style={{ fontSize: "1.5rem" }}>{g.icon}</span>
                <span style={{ fontWeight: 700, color: "#1a2a6c", fontSize: "0.95rem" }}>{g.title}</span>
              </div>
              <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
                {g.points.map(pt => (
                  <li key={pt} style={{ display: "flex", gap: "8px", alignItems: "flex-start", color: "#555", fontSize: "0.87rem", marginBottom: "6px" }}>
                    <span style={{ color: "#e87722", fontWeight: 700, flexShrink: 0 }}>✓</span>{pt}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section style={{ background: "#f0f4ff", padding: "56px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.5rem", color: "#1a2a6c", marginBottom: "28px" }}>
            Frequently Asked Questions
          </h2>
          <FaqAccordion faqs={faqs} />
        </div>
      </section>

      {/* Experts on Subject Matter */}
      <section style={{ background: "#1a2a6c", color: "#fff", padding: "48px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.4rem", marginBottom: "12px" }}>
            Experts on Subject Matter in the UK and UAE
          </h2>
          <p style={{ color: "#c5d5f0", lineHeight: 1.8, marginBottom: "14px" }}>
            At our company, we employ more than 2000+ experts who specialize in different subjects and understand the standards established at universities within the UK and UAE. The advice provided by our experts on your dissertation is informed by research conducted specifically in your discipline of study.
          </p>
          <p style={{ color: "#c5d5f0", lineHeight: 1.8, marginBottom: "28px" }}>
            We offer dissertation help services in different fields through Tutors India. We have 2000+ subject experts that help students with their writing assignments in fields such as Management, Engineering, Science, Literature, Technology, Medicine, and many more.
          </p>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "10px", marginBottom: "28px" }}>
            {subjects.map(s => (
              <span key={s} style={{ background: "rgba(255,255,255,0.12)", border: "1px solid rgba(255,255,255,0.2)", color: "#fff", padding: "6px 16px", borderRadius: "20px", fontSize: "0.85rem" }}>{s}</span>
            ))}
          </div>
          <Link href="/our-writers/" style={{ color: "#f9c74f", fontWeight: 600, fontSize: "0.95rem" }}>Meet Our Writers →</Link>
        </div>
      </section>

      {/* Voice of Our Customer */}
      <TestimonialSlider testimonials={testimonials.map(t => ({ ...t, author: t.name }))} />

      {/* Related Services */}
      <section style={{ background: "#f0f4ff", padding: "48px 20px" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.3rem", color: "#1a2a6c", marginBottom: "20px" }}>Related Services</h2>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "12px" }}>
            {relatedServices.map(s => (
              <Link key={s.label} href={s.href} style={{ padding: "10px 22px", background: "#fff", border: "1px solid #dde2ef", borderRadius: "5px", color: "#1a2a6c", fontWeight: 600, fontSize: "0.96rem", textDecoration: "none" }}>{s.label}</Link>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section style={{ background: "linear-gradient(135deg,#1a2a6c 0%,#2563b0 100%)", color: "#fff", padding: "56px 20px", textAlign: "center" }}>
        <h2 style={{ fontFamily: "Merriweather,serif", fontSize: "1.6rem", marginBottom: "12px" }}>
          Start Your Dissertation Journey with Expert Academic Guidance
        </h2>
        <p style={{ color: "#c5d5f0", marginBottom: "28px", fontSize: "1rem" }}>
          Start your dissertation journey with expert academic guidance for students in the UK and UAE.
        </p>
        <div style={{ display: "flex", gap: "16px", justifyContent: "center", flexWrap: "wrap" }}>
          <Link href="/order-now/" style={{ padding: "12px 36px", background: "#e87722", color: "#fff", borderRadius: "5px", fontWeight: 700 }}>Order Now</Link>
          <Link href="/contact-us/" style={{ padding: "12px 36px", border: "2px solid rgba(255,255,255,0.5)", color: "#fff", borderRadius: "5px", fontWeight: 600 }}>Contact Us</Link>
        </div>
      </section>
    </>
  );
}
